# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x04task\"\x1b\n\x07Request\x12\x10\n\x08question\x18\x01 \x01(\t\";\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x1f\n\x08\x63ontexts\x18\x02 \x03(\x0b\x32\r.task.Context\"2\n\x07\x43ontext\x12\x14\n\x0cpage_content\x18\x01 \x01(\t\x12\x11\n\tmeta_data\x18\x02 \x03(\t2<\n\nRagService\x12.\n\x0b\x45xecuteTask\x12\r.task.Request\x1a\x0e.task.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=19
  _globals['_REQUEST']._serialized_end=46
  _globals['_RESPONSE']._serialized_start=48
  _globals['_RESPONSE']._serialized_end=107
  _globals['_CONTEXT']._serialized_start=109
  _globals['_CONTEXT']._serialized_end=159
  _globals['_RAGSERVICE']._serialized_start=161
  _globals['_RAGSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
